configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZGM5ODg1MjIxOGFmZmIzY2ViZDM2NDUyZThjY2JjM2ZlNWJhNmNjNWY4MzA0Y2RmZjVhYjlkYWQ1ZWQ0OTIyODVjZjViMjA5N2FiZDZlZTJmZTM3NGNjNWM0OGRhMmYxZjM1OGI5ODUyYmJlZDMyMThiZWMyMjc4NjUwMGU0ZmM=
